name: Citadel
version: 1.0
description: Plugins kit for Andrew.
author: Andrew
website: http://www.andrewnunley.com
main: com.andrewnunley.citadel.Citadel

commands:
  msg:
    description: Send mail to players that is saved on the server
    aliases: []
    usage: |
           /msg <recipient> <text>
  recall:
    description: Moves the player to the mark or spawn
    aliases: []
    usage: |
           /recall [args]
  mark:
    description: Set the mark for recall
    aliases: []
    usage: |
           /mark